{{- $alert := "CNPGPoolerUnavailable" -}}
{{- if not (has $alert .excludeRules) -}}
alert: {{ $alert }}
annotations:
  summary: PgBouncer has no available instances
  description: |-
    Pooler "{{ .labels.deployment }}" for cluster "{{ .namespace }}/{{ .cluster }}" has no
    available PgBouncer instances. Customer connections through this endpoint will fail.
  runbook_url: https://github.com/paradedb/charts/blob/main/charts/paradedb/docs/runbooks/CNPGPooler.md
expr: |
  kube_deployment_status_replicas_available{
    namespace="{{ .namespace }}",
    deployment=~"{{ .cluster }}-pooler-.+"
  } == 0
for: 5m
labels:
  severity: critical
  namespace: {{ .namespace }}
  cnpg_cluster: {{ .cluster }}
{{- end -}}
