{{- $alert := "CNPGClusterLogicalReplicationDisabled" -}}
{{- if not (has $alert .excludeRules) -}}
alert: {{ $alert }}
annotations:
  summary: ParadeDB CNPG Cluster logical replication subscription disabled
  description: |-
    ParadeDB CloudNativePG Cluster's "{{ .namespace }}/{{ .cluster }}" "{{ .subname }}" subscription has been disabled.
  runbook_url: https://github.com/paradedb/charts/blob/main/charts/paradedb/docs/runbooks/{{ $alert }}.md
expr: |
  label_replace(max by (namespace, job, subname) (time() - cnpg_pg_stat_subscription_enabled), "cluster", "$1", "job", ".+/(.+)") == 0
for: 5m
labels:
  severity: critical
  namespace: {{ .namespace }}
  cnpg_cluster: {{ .cluster }}
{{- end -}}
