{{- $alert := "CNPGClusterLogicalReplicationErrorsCritical" -}}
{{- if not (has $alert .excludeRules) -}}
{{- $errorSelector := printf "{namespace=%%q,job=%%q,subname=%%q,pod=~%q}" .podSelector -}}
{{- $applyQuery := printf "max(increase(cnpg_pg_stat_subscription_apply_error_count%s[5m]))" $errorSelector -}}
{{- $syncQuery := printf "max(increase(cnpg_pg_stat_subscription_sync_error_count%s[5m]))" $errorSelector -}}
alert: {{ $alert }}
annotations:
  summary: CNPG Cluster critical logical replication errors
  description: |-
    CloudNativePG Cluster's "{{ .namespace }}/{{ .cluster }}" "{{ .labels.subname }}" subscription has experienced {{ .value }} errors in the last 5 minutes.

    CRITICAL: High error rate indicates persistent replication issues requiring immediate attention. This could lead to significant data inconsistency or complete replication failure. Errors include both apply errors and sync errors. The subscription may stop working if errors continue.
  apply_errors: >-
    {{ printf "{{ with query (printf %q $labels.namespace $labels.job $labels.subname) }}{{ . | first | value | printf \"%%.2f\" }}{{ else }}unavailable{{ end }}" $applyQuery }}
  sync_errors: >-
    {{ printf "{{ with query (printf %q $labels.namespace $labels.job $labels.subname) }}{{ . | first | value | printf \"%%.2f\" }}{{ else }}unavailable{{ end }}" $syncQuery }}
  logs_url: https://github.com/paradedb/charts/blob/main/charts/paradedb/docs/runbooks/CNPGClusterLogicalReplicationErrors.md#diagnosis
  runbook_url: https://github.com/paradedb/charts/blob/main/charts/paradedb/docs/runbooks/CNPGClusterLogicalReplicationErrors.md
expr: |
  label_replace(max by (namespace, job, subname) (increase(cnpg_pg_stat_subscription_apply_error_count{namespace="{{ .namespace }}",pod=~"{{ .podSelector }}"}[5m]) + increase(cnpg_pg_stat_subscription_sync_error_count{namespace="{{ .namespace }}",pod=~"{{ .podSelector }}"}[5m])), "cluster", "$1", "job", ".+/(.+)") >= 5
for: 0m
labels:
  severity: critical
  namespace: {{ .namespace }}
  cnpg_cluster: {{ .cluster }}
{{- range $key, $val := .additionalLabels }}
  {{ $key }}: {{ $val | toString | quote }}
{{- end }}
{{- end -}}
